version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=${BACKEND_PORT}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - my-network

  prisma-studio:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    command: npx prisma studio
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "5556:5555"
    networks:
      - my-network

networks:
  my-network:
